// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASd4ygnzmFHzqc9uYbnmzil4zUV1s2kXw',
    appId: '1:1053026044417:web:f9e8f39f66b9f6a5d7ce00',
    messagingSenderId: '1053026044417',
    projectId: 'chatapp-66b9c',
    authDomain: 'chatapp-66b9c.firebaseapp.com',
    storageBucket: 'chatapp-66b9c.firebasestorage.app',
    measurementId: 'G-PJY1LD32YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbEjcfOpFOKjoTDNpf2q5WRNeG9zonhiQ',
    appId: '1:1053026044417:android:8c395406142dc95fd7ce00',
    messagingSenderId: '1053026044417',
    projectId: 'chatapp-66b9c',
    storageBucket: 'chatapp-66b9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAADfgv9UZiHZw8-NYcUut3dzmotTJ9zEM',
    appId: '1:1053026044417:ios:aefbf2243e05f98ad7ce00',
    messagingSenderId: '1053026044417',
    projectId: 'chatapp-66b9c',
    storageBucket: 'chatapp-66b9c.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASd4ygnzmFHzqc9uYbnmzil4zUV1s2kXw',
    appId: '1:1053026044417:web:1966b19cb9df03bad7ce00',
    messagingSenderId: '1053026044417',
    projectId: 'chatapp-66b9c',
    authDomain: 'chatapp-66b9c.firebaseapp.com',
    storageBucket: 'chatapp-66b9c.firebasestorage.app',
    measurementId: 'G-4YKZMEDZ7V',
  );

}